on: push
name: 🚀 Deploy website
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 📂 Deploy to mittwald space
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: src/
          remote_path: html/ssh-test-prb0r
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_PRIVATE_KEY }}